# Generated by Django 4.0.1 on 2022-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField()),
                ('sender_address', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
