# Generated by Django 4.0.1 on 2022-01-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime_received',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
